### ISSUE TITLE
Server starts while invalid configuration is provided

### ISSUE THREAD

**Issue by xela92** [porech/engarde#1]
tool: engarde-server
version: latest (github)
platform: Linux (Ubuntu Server 18.04)
issue: if a configuration file is created, it could have no "server" section and still it will start and listen to nothing.
details: 
```
./engarde-server 
INFO[0000] Listening on  
```
expected behaviour: it should exit with an error code like when no configuration file is found

**Comment by ale-rinaldi** [comment]
Can you please test builds at http://www.linuxzogno.org/engarde/builds/fix/1-check-config-parameters/ and ensure the problem is solved?

Thanks

**Comment by xela92** [comment]
I confirm that with the test builds it is working fine in those cases:

1. empty configuration
2. slightly modified configuration without compulsory information

both on client and server.

Thanks!
