### ISSUE TITLE
Excluding/Including not always saving state?

### ISSUE THREAD

**Issue by Marctraider** [porech/engarde#35]
Hi! Just noticed (maybe) a small bug, not exactly sure.

I excluded an interface yesterday and an hour later re-included it.

Now i look today it was included but says xxxxx seconds not received any data (basically 12 ish hours or so), so i excluded and reincluded it just now and it just works fine again instantly.

Maybe there is some small bug that not always properly saves the new state though the API?

**Comment by talalmash** [comment]
I also noticed something similar when one of the interfaces goes down and
up, needs ex/include to show 0 handshake and restored connection. Ended up
making a bridge with a dummy interface as the bridge never goes down. But
my modem has ethernet switch bug which reconnects every 10 hours or so,
same with my WISP PPPoE disconnecting during fog. This only happens after
running engarde for few days, bridging interface is my current workaround.
The log usually shows "cannot write to socket" or something similar per
interface disconnection.

**Comment by Marctraider** [comment]
I dont think i had any messages from the particular interface at all in the logs, just reflecting what I did on the engarde web interface

**Comment by talalmash** [comment]
My bad, I'll open a new issue once it happens again to confirm, maybe it's my aging SBC.

**Comment by ale-rinaldi** [comment]
Hello @Marctraider ,
thanks for the issue, it looks quite strange since the inclusion logic is the same for the UI visualization and for the transmission logic, but I will have a look at it. The (slower than I'd want) refactor will totally replace the way it works, by the way: it will be event-based and so it will for sure work in a more reliable way.

Thanks

**Comment by Marctraider** [comment]
Maybe it was an edge case or maybe it was something on my Debian, but I didn't touch anything OS/network level other than re-exclude/include and it magically started receiving packets again :)

Either way, all works great in general ^^

**Comment by talalmash** [comment]
> Maybe it was an edge case or maybe it was something on my Debian, but I didn't touch anything OS/network level other than re-exclude/include and it magically started receiving packets again :)
> 
> Either way, all works great in general ^^

Are you using keepalive on the wireguard interface? If so how many seconds?
