### ISSUE TITLE
is there a example for one interface with 2 ip?

### ISSUE THREAD

**Issue by InnotSagg** [porech/engarde#43]
for example one ipv4 with extra ipv6 ?

or two ipv4 with alias for same interface ?

for both server side and client side.

**Comment by ale-rinaldi** [comment]
Hello @InnotSagg , at the moment engarde can output just to an IP for each interface. This is quite annoying also if, for example, you have a single LAN with multiple gateways in it and you want to use engarde in this scenario.

I've seen a scenario like this, on Windows, where the user created different virtual network interfaces bridged to the main one, each one with its IP and gateway. The procedure is pretty much [the one described here](https://superuser.com/questions/1396033/windows-creating-virtual-interface-over-a-single-physical-interface/1396636#1396636).

I will work on it in a future release, however.

Thank you

**Comment by TalalMash** [comment]
IPVLAN works well and very easy to setup under Linux.
