### ISSUE TITLE
DNS/traffic issue

### ISSUE THREAD

**Issue by rtgoodwin** [porech/engarde#46]
First off, thanks for making this! I need a reliable failproof connection for "high stakes" streaming (ok it's comedy :) ). 

**Env**
* Client: macOS 10.15.7, WG latest app from App Store. 1 ethernet, 1 wifi connection, same internal network, to a single router and modem. 
* Server: I setup a new droplet at DO with https://github.com/jar-o/rotvpn (super simple btw). Ubuntu 20 I believe?

Put the engarde client locally, server remote. Used the sample config file but of course edited the destination, and edited the WG tunnel dest. 

Connected WG, connected engarde, as far as I can tell. The engarde client reports the new interface and doesn't complain. 

With engarde on, unable to ping (8.8.8.8 or 1.1.1.1 for example), nor DNS resolution. rotvpn installs unbound for encrypted DNS, but I get the sense that traffic wasn't flowing period, so not specifically a DNS issue. (I could be wrong about what destinations allow ICMP, to be fair). I checked all the ports that rotvpn opens, and tried to explicitly open any engarde port I could see, as well as setting unbound to accept traffic on all interfaces, from all client IP ranges. 

I don't know that it's an issue with DNS, but I'm also not sure how engarde comes into the picture at this point.

I know this is semi vague; I'm hoping for troubleshooting tips to "teach myself to fish" on it. 

Thanks in advance!

**Comment by ale-rinaldi** [comment]
Hello,

here it seems that there's some issue with the configuration itself, and so with the entire traffic flow, rather than just the DNS resolution.

May you please post your Wireguard and engarde config files, both for client and server? Of course without any key and public IP.

Thanks!

**Comment by rtgoodwin** [comment]
Thanks for the prompt response, will do when back at that system. Thanks!

**Comment by ale-rinaldi** [comment]
Hello, did you solve your issue? Thanks

**Comment by rtgoodwin** [comment]
My apologies, haven't had a chance to really test again. i'm confident it is a WG config issue, because otherwise your project wouldn't be working so well otherwise. I'll close this and if I can't solve it, let you know :) Sorry for keeping it open!

**Comment by ale-rinaldi** [comment]
No problem man, you may need any help with the configuration just drop a note :)
