### ISSUE TITLE
Can't access engarde.linuxzogno.org for downloading build file.

### ISSUE THREAD

**Issue by zxwanghongyi** [porech/engarde#65]
No respond from engarde.linuxzogno.org

This is Google's cache of https://engarde.linuxzogno.org/builds/testing/update-ng-9/windows/. It is a snapshot of the page as it appeared on 1 Jan 2022 11:34:05 GMT.

**Comment by ale-rinaldi** [comment]
Hi,
totally a fault on my side, sorry. I'll have it sorted out in the afternoon.
Thank you!

**Comment by zxwanghongyi** [comment]
Thanks!

**Comment by zxwanghongyi** [comment]
By the way, the image in README are not showing up too.

**Comment by ale-rinaldi** [comment]
Hi,
it should be working now. Also the images.
Thanks!
